FROM golang:1.23.2

WORKDIR /app

COPY /miiyagi-api/go.mod /miiyagi-api/go.sum ./

RUN go mod download

COPY /miiyagi-api .

RUN CGO_ENABLED=1 GOOS=linux go build -o /api-server

EXPOSE 8080

CMD ["/api-server"]
